spring:
    datasource:
        url: jdbc:h2:mem:ecommerce
        username: sa
        password: secret
        driver-class-name: org.h2.Driver
    sql:
      init:
          mode: never
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    h2:
      console:
          enabled: true
          path: /h2-console
