name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17 (OpenJDK)
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw

      - name: Build native image with Maven
        run: ./mvnw clean package -Pnative -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce:latest

      - name: Deploy to AWS EC2 using Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.DO_PORT }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce:latest
            docker stop ecommerce || true
            docker rm ecommerce || true
            docker run -d --name ecommerce -p 8080:8080 --network ec2-user_ecommerce-network ${{ secrets.DOCKER_HUB_USERNAME }}/ecommerce:latest
            
